[package]
name = "day_07"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atoi = "2"

[[bin]]
name = "day_07"
path = "src/main.rs"

[lib]
name = "day_07"
path = "src/lib.rs"
